#!/bin/bash

# TAPS
brew tap github/gh
brew tap homebrew/cask-fonts
brew tap homebrew/cask
brew tap homebrew/core
brew tap homebrew/services

# PACKAGES
brew install bat
brew install composer
brew install fish
brew install gh
brew install git
brew install mas
brew install mysql@5.7
brew install node@12
brew install php
brew install svtplay-dl
brew install thefuck
brew install yarn
brew install youtube-dl
brew install z
brew install zsh
brew install zsh-completions
brew install zsh-syntax-highlighting

# CASKS
brew cask install alfred
brew cask install appcleaner
brew cask install bitwarden
brew cask install blurred
brew cask install brave-browser
brew cask install devdocs
brew cask install dozer
brew cask install firefox
brew cask install github
brew cask install hyper
brew cask install iterm2
brew cask install imagealpha
brew cask install imageoptim
brew cask install kap
brew cask install postman
brew cask install responsively
brew cask install runjs
brew cask install slack
brew cask install spotify
brew cask install tableplus
brew cask install transmission
brew cask install visual-studio-code
brew cask install vlc

# Amphetamine
mas install 937984704
# Battery Indicator
mas install 1206020918
# Fantastical
mas install 975937182
# Slack
mas install 803453959
#  Glance – Quick Look Plugin
mas install 1513574319
# Logic Pro X 
mas install 634148309
# Magnet
mas install 441258766
# RunCat
mas install 1429033973
# Spark – Email App by Readdle
mas install 1176895641
# The Unarchiver
mas install 425424353
# Things 3
mas install 904280696
# Tim ∙ Simple Time Tracker
mas install 1449619230
# Tweetbot
mas install 1384080005