#!/bin/bash

npm install --global \
  alfred-dark-mode \
  alfred-kaomoji \
  imageoptim-cli \
  tree-node-cli \
  is-up-cli \
  public-ip-cli \
  alfred-npms \
  alfred-packagist \
  alfred-updater \
  empty-trash-cli \
  fast-cli \
  internal-ip-cli \
  npm-check-updates \
  trash-cli